openapi: "3.0.2"
info:
  title: Products events
  version: 1.0.0
  license:
    name: MIT-0

paths: {}

components:
  schemas:
    ProductCreated:
      x-amazon-events-source: ecommerce.products
      x-amazon-events-detail-type: ProductCreated
      description: Event emitted when a product is created.
      allOf:
        - $ref: "../../shared/resources/schemas.yaml#/EventBridgeHeader"
        - type: object
          properties:
            detail:
              $ref: "../../shared/resources/schemas.yaml#/Product"

    ProductModified:
      x-amazon-events-source: ecommerce.products
      x-amazon-events-detail-type: ProductModified
      description: Event emitted when a product is modified.
      allOf:
        - $ref: "../../shared/resources/schemas.yaml#/EventBridgeHeader"
        - type: object
          properties:
            detail:
              type: object
              properties:
                old:
                  $ref: "../../shared/resources/schemas.yaml#/Product"
                new:
                  $ref: "../../shared/resources/schemas.yaml#/Product"

    ProductDeleted:
      x-amazon-events-sources: ecommerce.products
      x-amazon-events-detail-type: ProductDeleted
      description: Event emitted when a product is deleted.
      allOf:
        - $ref: "../../shared/resources/schemas.yaml#/EventBridgeHeader"
        - type: object
          properties:
            detail:
              $ref: "../../shared/resources/schemas.yaml#/Product"
